[gson] Self package import breaks clients
Bug 509535 - java.lang.NoClassDefFoundError:
com/google/gson/annotations/JsonAdapter 

Change-Id: I5b321ff194f864a312eea1ff0e5e23f669d13c1b
Signed-off-by: Dennis Huebner <dennis.huebner@gmail.com>